HE = {
 'CP1':'The light machine','CP2':'Lenses and lasers','CP3':'The advanced fab','CP4':'Advanced packaging','CP5':'High-bandwidth memory',
 'CP6':'Silicon wafers','CP7':'Resist and chemicals','CP8':"Ajinomoto's film",'CP9':'EUV mask blanks','CP10':'Lasers and fiber',
 'CP11':'Turbines and transformers','CP12':'Critical minerals','CP13':'Chip testing','CP14':'Design tools'}
BLURB = {
 'CP1':'ASML is the only company on earth that builds EUV machines. About 65 a year, and that is a physical ceiling on how many advanced chips the world can make.',
 'CP2':'Zeiss for the optics, TRUMPF for the laser. Both private, both German. No substitute, and no way to invest in them.',
 'CP3':'TSMC makes roughly 90% of chips below 7nm, all of it in Taiwan. Intel and Samsung are insurance, not replacements.',
 'CP4':'CoWoS: about 70% at TSMC. The gap between demand and supply has narrowed from 20% to 10%.',
 'CP5':'HBM: three makers only, nearly half the cost of an AI accelerator, sold out through 2027.',
 'CP6':'Shin-Etsu and SUMCO hold more than half of the world\'s silicon wafers. Japan supplies more than half of all substrates.',
 'CP7':'Over 90% of EUV photoresist sits with three Japanese companies. One bad batch cost TSMC about $550M in 2019.',
 'CP8':'Ajinomoto, a food company, makes over 95% of the ABF film inside every AI chip package. A second plant only in 2032.',
 'CP9':'AGC and HOYA hold about 93% of EUV mask blanks. No qualified substitute at volume.',
 'CP10':'Chinese vendors hold about 60% of transceivers. The FCC restriction tightens the bottleneck instead of loosening it.',
 'CP11':'GE Vernova and Siemens Energy: turbine slots booked to 2030, transformers 4-5 years out. Coil-winding labor is the real constraint.',
 'CP12':'China holds 98% of gallium and 77% of germanium. The export-ban suspension expires on November 27, 2026.',
 'CP13':'Advantest holds 66% of SoC testers. Testing HBM4 takes twice as long as HBM2E.',
 'CP14':'Synopsys, Cadence and Siemens hold 70-80% of design tools. The incumbents buy the challengers rather than being displaced.',
}
STAGE = {'research':'research','pilot':'pilot','qualified':'qualified','volume':'volume'}

W = [
 ('orcl_q1',   '2026-09-10', True,  'Oracle Q1 FY27',           'ORCL',   [],            "How much Oracle is buying: capex pace and RPO. After the big four, it is NVIDIA's and AMD's hungriest customer.", 'FY27 capex guidance and the RPO number', ['nvda','amd','vrt'], []),
 ('mu_fq4',    '2026-09-30', True,  'Micron FQ4',               'MU',     ['CP5'],       'Does Micron reach its HBM share target, and how fast is HBM4 capacity coming.', 'HBM share target for 2027 and capex', ['mu'], ['skhynix','samsung']),
 ('smsg_pre',  '2026-10-08', False, 'Samsung Q3 (preliminary)', '005930', ['CP5','CP3'], "Do memory profits confirm that Samsung's HBM4 is shipping to NVIDIA in volume.", 'Memory division operating profit vs prior quarter', ['samsung'], ['skhynix']),
 ('asml_q3',   '2026-10-14', True,  'ASML Q3',                  'ASML',   ['CP1','CP2'], "How many EUV machines were ordered, how many High-NA, and China's share. This is the ceiling on everything below.", 'EUV bookings, High-NA units, 2027 outlook', ['asml'], []),
 ('tsm_q3',    '2026-10-15', True,  'TSMC Q3',                  'TSM',    ['CP3','CP4'], 'Actual CoWoS capacity, the 2nm ramp, and whether it commits to High-NA for A14 or defers again.', 'A CoWoS capacity number for end-2026 and 2027 capex', ['tsmc','asml'], ['intc','samsung']),
 ('clf_q3',    '2026-10-19', True,  'Cleveland-Cliffs Q3',      'CLF',    ['CP11'],      'The only US maker of electrical steel: is the Butler upgrade on time, and what is transformer demand doing.', 'Update on the $195M upgrade and GOES pricing', ['clf'], []),
 ('intc_q3',   '2026-10-22', True,  'Intel Q3',                 'INTC',   ['CP3'],       'Is there a committed external customer for 14A. The CEO said decisions would land in the second half. The sharpest test on this list.', 'A customer name, or "decisions deferred"', ['intc'], ['tsmc']),
 ('shecy_h1',  '2026-10-23', True,  'Shin-Etsu H1',             'SHECY',  ['CP6','CP7'], 'Demand for silicon wafers and EUV resist. Down 19% this quarter — do the numbers explain why.', '300mm wafer shipments and H2 outlook', ['shinetsu'], ['globalwafers']),
 ('skh_q3',    '2026-10-23', False, 'SK hynix Q3',              '000660', ['CP5'],       'HBM share, HBM4 pricing, and whether the base die at TSMC is hurting margins.', 'HBM share and HBM4 vs HBM3E pricing', ['skhynix'], ['mu','samsung']),
 ('amkr_q3',   '2026-10-26', True,  'Amkor Q3',                 'AMKR',   ['CP4'],       'Is there an anchor customer for the Peoria, Arizona plant. This is what turns advanced packaging from Taiwanese into American.', 'A customer name for Arizona', ['amkr'], ['tsmc']),
 ('cdns_q3',   '2026-10-26', True,  'Cadence Q3',               'CDNS',   ['CP14'],      'China revenue after the restrictions were lifted, and how much of the growth comes from AI tools.', "China's share of revenue", ['cdns'], []),
 ('ter_q3',    '2026-10-27', True,  'Teradyne Q3',              'TER',    ['CP13'],      'Is Teradyne taking HBM and GPU test share from Advantest. The tell: "merchant GPU" with no customer named.', 'HBM/GPU test orders and a customer name', ['ter'], ['advantest']),
 ('gev_q3',    '2026-10-28', True,  'GE Vernova Q3',            'GEV',    ['CP11'],      'How many turbine slots remain for 2029-2030, and what the transformer lead time is.', 'GW signed and reserved, LPT lead time', ['gev'], ['msft','amzn','googl']),
 ('lrcx_q1',   '2026-10-28', True,  'Lam Research FQ1',         'LRCX',   ['CP3','CP5'], 'Customer mix: Samsung 16%, TSMC 15%, hynix 12%, Micron 12%. A change in the order is a change in who is building.', 'Customers above 10% and WFE outlook', ['lrcx'], []),
 ('teck_q3',   '2026-10-28', True,  'Teck Q3',                  'TECK',   ['CP12'],      'Doubling germanium at Trail — is it on time before the Chinese suspension expires.', 'Germanium output and timeline', ['teck'], []),
 ('googl_q3',  '2026-10-28', True,  'Alphabet Q3',              'GOOGL',  [],            'Capex for 2026 and 2027. The big four are $730B — any change here moves the whole map.', 'Capex guidance', ['nvda','avgo','tsmc'], []),
 ('adv_h1',    '2026-10-28', False, 'Advantest H1',             '6857',   ['CP13'],      'SoC tester share (66%) and what the Korean testers are doing at SK hynix.', 'SoC share and full-year outlook', ['advantest'], ['ter']),
 ('smsg_q3',   '2026-10-28', False, 'Samsung Q3 (full)',        '005930', ['CP5','CP3'], 'HBM4 detail: how much goes to NVIDIA, and what is happening at 2nm in the foundry.', 'HBM share and SF2 yield', ['samsung'], ['skhynix','tsmc']),
 ('hanmi_q3',  '2026-10-29', False, 'Hanmi Semiconductor Q3',   '042700', ['CP4','CP5'], 'The supplier that lost half its HBM4 bonder orders to ASMPT. Has the bleeding stopped.', 'TC bonder orders and a customer name', ['hanmi'], ['asmpt']),
 ('asx_q3',    '2026-10-29', True,  'ASE Q3',                   'ASX',    ['CP4'],       'Will ASE name its CoWoS-equivalent capacity. That is what dilutes the concentration at TSMC.', 'An advanced-packaging capacity number', ['ase'], ['tsmc']),
 ('axti_q3',   '2026-10-29', True,  'AXT Q3',                   'AXTI',   ['CP10'],      'InP substrates — all made in China under license. Price up 250%. Are the licenses continuing.', 'InP revenue and MOFCOM license status', ['axti'], ['lite','cohr']),
 ('entg_q3',   '2026-10-29', True,  'Entegris Q3',              'ENTG',   ['CP3'],       'TSMC is 16% of revenue. A change here gauges the pace of 2nm construction.', "TSMC's share and outlook", ['entegris'], []),
 ('amzn_q3',   '2026-10-29', True,  'Amazon Q3',                'AMZN',   [],            'Capex and Trainium: how much compute is moving to in-house chips instead of NVIDIA.', 'Capex guidance and any Trainium mention', ['alab','crdo','mrvl'], ['nvda']),
 ('hwm_q3',    '2026-10-29', True,  'Howmet Q3',                'HWM',    ['CP11'],      'Turbine blade castings — 60-90 weeks per batch. Is capacity growing.', 'IGT orders', ['hwm'], []),
 ('mpwr_q3',   '2026-10-29', True,  'Monolithic Power Q3',      'MPWR',   ['CP3'],       'Power content in Blackwell and Rubin. A quiet supplier every chip passes through.', 'Datacenter revenue', ['mpwr'], []),
 ('hoya_h1',   '2026-10-30', False, 'HOYA H1',                  '7741',   ['CP9'],       "EUV mask blanks: is the third plant in Singapore on time, and what is AGC's share.", 'Mask blank revenue and outlook', ['hoya'], []),
 ('cohr_q1',   '2026-11-05', False, 'Coherent FQ1',             'COHR',   ['CP10'],      'Down 30% this quarter. Is 1.6T taking off, and is the FCC really restricting the Chinese vendors.', '1.6T orders and any FCC comment', ['cohr','fn'], []),
 ('ajin_h1',   '2026-11-05', False, 'Ajinomoto H1',             '2802',   ['CP8'],       'ABF film: volumes and prices after a 30% increase. Operating margin above 50%.', 'Electronic materials revenue and margin', ['ajinomoto'], []),
 ('sumco_q3',  '2026-11-06', False, 'SUMCO Q3',                 '3436',   ['CP6'],       "300mm wafer shipments. China's NSIG is approaching 1.2 million a month.", 'Shipment outlook', ['sumco'], []),
 ('mofcom_re', '2026-11-10', True,  'China — rare-earth suspension expires', 'MOFCOM', ['CP12'], 'A hard date. If the suspension is not extended, magnet controls return.', 'Official notice: extension or expiry', ['mp'], []),
 ('tel_q2',    '2026-11-10', False, 'Tokyo Electron Q2',        '8035',   ['CP3'],       "Sole supplier of EUV resist coaters. China's share of revenue.", "China's share and outlook", ['tel'], []),
 ('amat_q4',   '2026-11-12', False, 'Applied Materials FQ4',    'AMAT',   ['CP3'],       'China, HBM, and 2027. AMAT is the health gauge of the whole equipment layer.', '2027 WFE outlook', ['amat','lrcx','klac'], []),
 ('sie_fy',    '2026-11-12', False, 'Siemens Energy FY26',      'ENR',    ['CP11'],      'Transformer lead times. A drop below three years means the constraint is easing.', 'LPT lead time and backlog', ['siemensenergy'], ['gev']),
 ('nvda_q3',   '2026-11-19', False, 'NVIDIA Q3 FY27',           'NVDA',   ['CP5','CP3','CP4'], 'All of it: HBM supplier mix, Rubin, and NVHBM moving the base die in-house.', 'Memory supplier mentions and Q4 guidance', ['tsmc','skhynix','mu'], []),
 ('mofcom_ga', '2026-11-27', True,  'China — gallium/germanium suspension expires', 'MOFCOM', ['CP12'], 'A hard date. 98% of gallium. Extension, or back to the ban.', 'Official notice', ['aa','teck','mtln'], []),
 ('semi_smg',  '2026-12-10', False, 'SEMI — Q3 silicon shipments', 'SEMI', ['CP6'],       "The industry's quarterly number. Are the Chinese taking share.", 'MSI shipped and year-over-year change', ['globalwafers'], ['shinetsu','sumco']),
 ('absolics',  '2026-12-31', False, 'Absolics — glass-core substrate', 'SKC', ['CP8','CP4'], 'Package-level results or a customer name. The cleanest binary test in materials.', 'A customer announcement or credible results', ['skc'], ['ajinomoto','ibiden']),
 ('lsrc_q2',   '2027-01-27', False, 'Lasertec Q2',              '6920',   ['CP9'],       'Sole source for EUV mask inspection. High-NA orders.', 'Orders and outlook', ['lasertec'], []),
 ('spie',      '2027-02-22', False, 'SPIE Advanced Lithography','—',      ['CP7','CP1'], 'Metal-oxide resist in production, and any hint of a second optics supplier for ASML.', 'TSMC/Intel talks on dry resist', ['lrcx'], ['tok','shinetsu']),
]
