HE = {
 'CP1':'The light machine','CP2':'Lenses and lasers','CP3':'The advanced fab','CP4':'Advanced packaging','CP5':'High-bandwidth memory',
 'CP6':'Silicon wafers','CP7':'Resist and chemicals','CP8':"Ajinomoto's film",'CP9':'EUV mask blanks','CP10':'Lasers and fiber',
 'CP11':'Turbines and transformers','CP12':'Critical minerals','CP13':'Chip testing','CP14':'Design tools'}
BLURB = {
 'CP1':'ASML is the only company on earth that builds EUV machines. About 65 a year, and that is a physical ceiling on how many advanced chips the world can make.',
 'CP2':'Zeiss for the optics, TRUMPF for the laser. Both private, both German. No substitute, and no way to invest in them.',
 'CP3':'TSMC makes roughly 90% of chips below 7nm, all of it in Taiwan. Intel and Samsung are insurance, not replacements.',
 'CP4':'CoWoS: about 70% at TSMC. The gap between demand and supply has narrowed from 20% to 10%.',
 'CP5':'HBM: three makers only, nearly half the cost of an AI accelerator, sold out through 2027.',
 'CP6':'Shin-Etsu and SUMCO hold more than half of the world\'s silicon wafers. Japan supplies more than half of all substrates.',
 'CP7':'Over 90% of EUV photoresist sits with three Japanese companies. One bad batch cost TSMC about $550M in 2019.',
 'CP8':'Ajinomoto, a food company, makes over 95% of the ABF film inside every AI chip package. A second plant only in 2032.',
 'CP9':'AGC and HOYA hold about 93% of EUV mask blanks. No qualified substitute at volume.',
 'CP10':'Chinese vendors hold about 60% of transceivers. The FCC restriction tightens the bottleneck instead of loosening it.',
 'CP11':'GE Vernova and Siemens Energy: turbine slots booked to 2030, transformers 4-5 years out. Coil-winding labor is the real constraint.',
 'CP12':'China holds 98% of gallium and 77% of germanium. The export-ban suspension expires on November 27, 2026.',
 'CP13':'Advantest holds 66% of SoC testers. Testing HBM4 takes twice as long as HBM2E.',
 'CP14':'Synopsys, Cadence and Siemens hold 70-80% of design tools. The incumbents buy the challengers rather than being displaced.',
}
STAGE = {'research':'research','pilot':'pilot','qualified':'qualified','volume':'volume'}

W = [
 ('orcl_q1'  , '2026-09-10', True , 'Oracle Q1 FY27'                              , 'ORCL'  , []                   , ['nvda', 'amd', 'vrt'], []),
 ('mu_fq4'   , '2026-09-30', True , 'Micron FQ4'                                  , 'MU'    , ['CP5']              , ['mu'], ['skhynix', 'samsung']),
 ('smsg_pre' , '2026-10-08', False, 'Samsung Q3 (preliminary)'                    , '005930', ['CP5', 'CP3']       , ['samsung'], ['skhynix']),
 ('asml_q3'  , '2026-10-14', True , 'ASML Q3'                                     , 'ASML'  , ['CP1', 'CP2']       , ['asml'], []),
 ('tsm_q3'   , '2026-10-15', True , 'TSMC Q3'                                     , 'TSM'   , ['CP3', 'CP4']       , ['tsmc', 'asml'], ['intc', 'samsung']),
 ('clf_q3'   , '2026-10-19', True , 'Cleveland-Cliffs Q3'                         , 'CLF'   , ['CP11']             , ['clf'], []),
 ('intc_q3'  , '2026-10-22', True , 'Intel Q3'                                    , 'INTC'  , ['CP3']              , ['intc'], ['tsmc']),
 ('shecy_h1' , '2026-10-23', True , 'Shin-Etsu H1'                                , 'SHECY' , ['CP6', 'CP7']       , ['shinetsu'], ['globalwafers']),
 ('skh_q3'   , '2026-10-23', False, 'SK hynix Q3'                                 , '000660', ['CP5']              , ['skhynix'], ['mu', 'samsung']),
 ('amkr_q3'  , '2026-10-26', True , 'Amkor Q3'                                    , 'AMKR'  , ['CP4']              , ['amkr'], ['tsmc']),
 ('cdns_q3'  , '2026-10-26', True , 'Cadence Q3'                                  , 'CDNS'  , ['CP14']             , ['cdns'], []),
 ('ter_q3'   , '2026-10-27', True , 'Teradyne Q3'                                 , 'TER'   , ['CP13']             , ['ter'], ['advantest']),
 ('gev_q3'   , '2026-10-28', True , 'GE Vernova Q3'                               , 'GEV'   , ['CP11']             , ['gev'], ['msft', 'amzn', 'googl']),
 ('lrcx_q1'  , '2026-10-28', True , 'Lam Research FQ1'                            , 'LRCX'  , ['CP3', 'CP5']       , ['lrcx'], []),
 ('teck_q3'  , '2026-10-28', True , 'Teck Q3'                                     , 'TECK'  , ['CP12']             , ['teck'], []),
 ('googl_q3' , '2026-10-28', True , 'Alphabet Q3'                                 , 'GOOGL' , []                   , ['nvda', 'avgo', 'tsmc'], []),
 ('adv_h1'   , '2026-10-28', False, 'Advantest H1'                                , '6857'  , ['CP13']             , ['advantest'], ['ter']),
 ('smsg_q3'  , '2026-10-28', False, 'Samsung Q3 (full)'                           , '005930', ['CP5', 'CP3']       , ['samsung'], ['skhynix', 'tsmc']),
 ('hanmi_q3' , '2026-10-29', False, 'Hanmi Semiconductor Q3'                      , '042700', ['CP4', 'CP5']       , ['hanmi'], ['asmpt']),
 ('asx_q3'   , '2026-10-29', True , 'ASE Q3'                                      , 'ASX'   , ['CP4']              , ['ase'], ['tsmc']),
 ('axti_q3'  , '2026-10-29', True , 'AXT Q3'                                      , 'AXTI'  , ['CP10']             , ['axti'], ['lite', 'cohr']),
 ('entg_q3'  , '2026-10-29', True , 'Entegris Q3'                                 , 'ENTG'  , ['CP3']              , ['entegris'], []),
 ('amzn_q3'  , '2026-10-29', True , 'Amazon Q3'                                   , 'AMZN'  , []                   , ['alab', 'crdo', 'mrvl'], ['nvda']),
 ('hwm_q3'   , '2026-10-29', True , 'Howmet Q3'                                   , 'HWM'   , ['CP11']             , ['hwm'], []),
 ('mpwr_q3'  , '2026-10-29', True , 'Monolithic Power Q3'                         , 'MPWR'  , ['CP3']              , ['mpwr'], []),
 ('hoya_h1'  , '2026-10-30', False, 'HOYA H1'                                     , '7741'  , ['CP9']              , ['hoya'], []),
 ('cohr_q1'  , '2026-11-05', False, 'Coherent FQ1'                                , 'COHR'  , ['CP10']             , ['cohr', 'fn'], []),
 ('ajin_h1'  , '2026-11-05', False, 'Ajinomoto H1'                                , '2802'  , ['CP8']              , ['ajinomoto'], []),
 ('sumco_q3' , '2026-11-06', False, 'SUMCO Q3'                                    , '3436'  , ['CP6']              , ['sumco'], []),
 ('mofcom_re', '2026-11-10', True , 'China — rare-earth suspension expires'       , 'MOFCOM', ['CP12']             , ['mp'], []),
 ('tel_q2'   , '2026-11-10', False, 'Tokyo Electron Q2'                           , '8035'  , ['CP3']              , ['tel'], []),
 ('amat_q4'  , '2026-11-12', False, 'Applied Materials FQ4'                       , 'AMAT'  , ['CP3']              , ['amat', 'lrcx', 'klac'], []),
 ('sie_fy'   , '2026-11-12', False, 'Siemens Energy FY26'                         , 'ENR'   , ['CP11']             , ['siemensenergy'], ['gev']),
 ('nvda_q3'  , '2026-11-19', False, 'NVIDIA Q3 FY27'                              , 'NVDA'  , ['CP5', 'CP3', 'CP4'], ['tsmc', 'skhynix', 'mu'], []),
 ('mofcom_ga', '2026-11-27', True , 'China — gallium/germanium suspension expires', 'MOFCOM', ['CP12']             , ['aa', 'teck', 'mtln'], []),
 ('semi_smg' , '2026-12-10', False, 'SEMI — Q3 silicon shipments'                 , 'SEMI'  , ['CP6']              , ['globalwafers'], ['shinetsu', 'sumco']),
 ('absolics' , '2026-12-31', False, 'Absolics — glass-core substrate'             , 'SKC'   , ['CP8', 'CP4']       , ['skc'], ['ajinomoto', 'ibiden']),
 ('lsrc_q2'  , '2027-01-27', False, 'Lasertec Q2'                                 , '6920'  , ['CP9']              , ['lasertec'], []),
 ('spie'     , '2027-02-22', False, 'SPIE Advanced Lithography'                   , '—'     , ['CP7', 'CP1']       , ['lrcx'], ['tok', 'shinetsu']),
]
